name: job_board
version: 1.0.0
config-version: 2

profile: stg

model-paths: ["models"]

models:
  job_board:
    +materialized: table

    models:
      silver:
        +schema: dbt_silver

      gold:
        +schema: dbt_gold